version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  W2_generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_W2
    outputs:
      highly_sensitive:
        cohort: output/input_W2.csv

  01_hhClassif_cr_analysis_dataset:
    run: stata-mp:latest analysis/01_hhClassif_cr_analysis_dataset.do MAIN
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        allvars: output/hhClassif_analysis_datasetMAIN.dta
        allvarsEthMiss: output/hhClassif_analysis_dataset_with_missing_ethnicityMAIN.dta
        allVarsAgeSpline: output/hhClassif_analysis_dataset_ageband_*MAIN.dta 
        allVarsAgeStratStset: output/hhClassif_analysis_dataset_STSET_*_ageband_*MAIN.dta 
      moderately_sensitive:
        log: logs/01_hhClassif_cr_analysis_dataset.log

  01_hhClassif_cr_analysis_dataset_W2:
    run: stata-mp:latest analysis/01_hhClassif_cr_analysis_dataset.do W2
    needs: [W2_generate_cohort]
    outputs:
      highly_sensitive:
        allvars: output/hhClassif_analysis_datasetW2.dta
        allvarsEthMiss: output/hhClassif_analysis_dataset_with_missing_ethnicityW2.dta
        allVarsAgeSpline: output/hhClassif_analysis_dataset_ageband_*W2.dta 
        allVarsAgeStratStset: output/hhClassif_analysis_dataset_STSET_*_ageband_*W2.dta 
      moderately_sensitive:
        log: logs/01_hhClassif_cr_analysis_dataset_W2.log

  02_hhClassif_an_data_checks:
    run: stata-mp:latest analysis/02_hhClassif_an_data_checks.do MAIN
    needs: [01_hhClassif_cr_analysis_dataset]
    outputs:
      moderately_sensitive:
        log: logs/02_hhClassif_an_data_checks.log

  02_hhClassif_an_data_checks_W2:
    run: stata-mp:latest analysis/02_hhClassif_an_data_checks.do W2
    needs: [01_hhClassif_cr_analysis_dataset_W2]
    outputs:
      moderately_sensitive:
        log: logs/02_hhClassif_an_data_checks_W2.log

  03_hhClassif_an_descriptive_table_1:
    run: stata-mp:latest analysis/03_hhClassif_an_descriptive_table_1.do MAIN
    needs: [01_hhClassif_cr_analysis_dataset]
    outputs:
      moderately_sensitive:
        log: logs/03_hhClassif_an_descriptive_table_1.log
        tableTxt: output/table1_hhClassif.txt
        tableExcel: output/table1_hhClassif.xlsx

  03_hhClassif_an_descriptive_table_1_W2:
    run: stata-mp:latest analysis/03_hhClassif_an_descriptive_table_1.do W2
    needs: [01_hhClassif_cr_analysis_dataset_W2]
    outputs:
      moderately_sensitive:
        log: logs/03_hhClassif_an_descriptive_table_1_W2.log
        tableTxt: output/table1_hhClassif_W2.txt
        tableExcel: output/table1_hhClassif_W2.xlsx

  04_hhClassif_an_univariable_analysis:
    needs: [01_hhClassif_cr_analysis_dataset]
    run: stata-mp:latest analysis/04_hhClassif_an_univariable_analysis.do MAIN
    outputs:
      moderately_sensitive:
        log: logs/04_hhClassif_an_univariable_analysis_MAIN.log
        data: output/an_univariable_cox_models_*_AGESEX_ageband_*MAIN.ster

  04_hhClassif_an_univariable_analysis_W2:
    needs: [01_hhClassif_cr_analysis_dataset_W2]
    run: stata-mp:latest analysis/04_hhClassif_an_univariable_analysis.do W2
    outputs:
      moderately_sensitive:
        log: logs/04_hhClassif_an_univariable_analysis_W2.log
        data: output/an_univariable_cox_models_*_AGESEX_ageband_*W2.ster

  05_hhClassif_an_multivariable_analysis:
    needs: [01_hhClassif_cr_analysis_dataset]
    run: stata-mp:latest analysis/05_hhClassif_an_multivariable_analysis.do MAIN
    outputs:
      moderately_sensitive:
        log: logs/05_hhClassif_an_multivariable_analysis_MAIN.log
        data: output/an_multivariable_cox_models_*_AGESEX_ageband_*MAIN.ster
        data2: output/an_multivariable_cox_models_*_AGESEX_ageband_*MAIN_eth5Interaction.ster

  05_hhClassif_an_multivariable_analysis_W2:
    needs: [01_hhClassif_cr_analysis_dataset_W2]
    run: stata-mp:latest analysis/05_hhClassif_an_multivariable_analysis.do W2
    outputs:
      moderately_sensitive:
        log: logs/05_hhClassif_an_multivariable_analysis_W2.log
        data: output/an_multivariable_cox_models_*_AGESEX_ageband_*W2.ster
        data2: output/an_multivariable_cox_models_*_AGESEX_ageband_*W2_eth5Interaction.ster

    
 



  
