version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  prepare_data:
    run: stata-mp:latest analysis/01_hhClassif_cr_analysis_dataset.do
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        allvars: output/hhClassif_analysis_dataset.dta
      moderately_sensitive:
        log1: released_outputs/01_hhClassif_cr_analysis_dataset.log

  data_checks:
    run: stata-mp:latest analysis/02_hhClassif_an_data_checks.do
    needs: [prepare_data]
    outputs:
      moderately_sensitive:
        log: released_outputs/02_hhClassif_an_data_checks.log

  output_table1:
    run: stata-mp:latest analysis/03b_hhClassif_an_descriptive_table_1.do
    needs: [prepare_data]
    outputs:
      moderately_sensitive:
        log: released_outputs/03b_hhClassif_an_descriptive_table_1.log
        table1text: output/table1_hhClassif.txt
        table1excel: output/table1_hhClassif.xlsx



  
